global:
  scrape_interval:     30s
  evaluation_interval: 30s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:

  - job_name: local_node
    static_configs:
      - targets: ['node_exporter:9100']


